steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: Build Dataflow Flex Template
    args: ['dataflow', 'flex-template', 'build',
           'gs://$_DATAFLOW_BASE_BUCKET/$_DATAFLOW_TEMPLATE_NAME.json',
           '--image-gcr-path=$_REGION_ID-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPOSITORY/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA',
           '--flex-template-base-image=PYTHON3',
           '--sdk-language=PYTHON',
           '--py-path=.',
           '--env=FLEX_TEMPLATE_PYTHON_PY_FILE=$_DATAFLOW_PYTHON_FILE_PATH',
           '--env=FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=$_DATAFLOW_REQUIREMENTS_FILE_PATH'
    ]
    waitFor: ['-']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: Run Dataflow Flex Template
    args: ['dataflow', 'flex-template', 'run', '$_DATAFLOW_JOB_NAME',
           '--template-file-gcs-location=gs://$_DATAFLOW_BASE_BUCKET/$_DATAFLOW_TEMPLATE_NAME.json',
           '--parameters=project_id=$PROJECT_ID,--emergency_events_subscription=$_EMER_SUB,--vehicle_subscription=$EMER_UBI,--big_query_dataset=$BQ,--big_query_table_matched=$_BQ_DATASET,--big_query_table_no_matched=$_BQ_SATASET_NO,--no_matched_topic=$_NO_MATCH_TOP,--table_sql:$_SQL,--streamlit_topic:$_STR',
           '--max-workers=1'
    ]
    waitFor: ['Build Dataflow Flex Template']
options:
  logging: STACKDRIVER_ONLY
substitutions:
  _DATAFLOW_BASE_BUCKET: dataflow-bucket-joan-alex-antoni-32
  _DATAFLOW_JOB_NAME: dataflow-build
  _DATAFLOW_TEMPLATE_NAME: template.json
  _REGION_ID: europe-west6
  _ARTIFACT_REGISTRY_REPOSITORY: dataflow-build
  _ARTIFACT_REGISTRY_IMAGE_NAME: dataflow-build
  _DATAFLOW_PYTHON_FILE_PATH: .\DataFlow\data-project.py
  _DATAFLOW_REQUIREMENTS_FILE_PATH: .\DataFlow\requirements.txt
  _EMER_SUB: emergencias_events-sub
  _EMER_UBI: emergencias_ubi_autos-sub
  _BQ: emergencia_eventos
  _BQ_DATASET: emergencias-macheadas
  _BQ_SATASET_NO: emergencias-no-macheadas
  _NO_MATCH_TOP: no_matched
  _SQL: recursos
  _STR: streamlit
