steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "--tag=gcr.io/$PROJECT_ID/emergencia-app"
      - "--file=Dockerfile"
      - .

images:
  - "gcr.io/$PROJECT_ID/emergencia-app"
