# Usar una imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo de requisitos (si existe) y el script de Streamlit
COPY requirements.txt ./
COPY emergencia_app.py ./

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt || pip install streamlit

# Exponer el puerto por defecto de Streamlit
ENV STREAMLIT_SERVER_PORT=8080
EXPOSE 8080

# Comando para ejecutar Streamlit
CMD ["streamlit", "run", "emergencia_app.py", "--server.port=8501", "--server.address=0.0.0.0"]