apiVersion: 1

datasources:
  - name: BigQuery
    type: marcusolsson-bigquery-datasource
    access: proxy
    jsonData:
      authenticationType: jwt
      defaultProject: splendid-strand-452918-e6
    secureJsonData:
      clientEmail: tu-servicio@tu-proyecto.iam.gserviceaccount.com
      privateKey: |
        -----BEGIN PRIVATE KEY-----
        TU_CLAVE_PRIVADA_EN_LÍNEAS
        -----END PRIVATE KEY-----
