{
 "title": "Emergencias",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total emergencias atendidas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "splendid-strand-452918-e6",
     "rawSql": "SELECT COUNT(*) AS total FROM `emergencia_eventos.emergencias-macheadas`;\n\n\n"
    }
   ]
  },
  {
   "title": "Emergencias NO atendidas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "splendid-strand-452918-e6",
     "rawSql": "SELECT COUNT(*) AS total FROM `emergencia_eventos.emergencias-no-macheadas`;\n"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta promedio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "splendid-strand-452918-e6",
     "rawSql": "SELECT ROUND(AVG(tiempo_respuesta), 2) AS tiempo_promedio FROM `emergencia_eventos.emergencias-macheadas`;\n\n"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta por servicio",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "project": "splendid-strand-452918-e6",
     "rawSql": "SELECT \n  servicio_evento,\n  ROUND(AVG(tiempo_respuesta), 2) AS tiempo_promedio,\n  MAX(tiempo_respuesta) AS tiempo_max,\n  MIN(tiempo_respuesta) AS tiempo_min\nFROM `emergencia_eventos.emergencias-macheadas`\nGROUP BY servicio_evento\n"
    }
   ]
  },
  {
   "title": "Localización Emergencias",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "project": "splendid-strand-452918-e6",
     "rawSql": "SELECT \n  lat_evento AS latitude,\n  lon_evento AS longitude,\n  servicio_evento\nFROM `emergencia_eventos.emergencias-macheadas`;\n"
    }
   ]
  },
  {
   "title": "Distribución por servicio de emergencias",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 15 },
   "targets": [
    {
     "project": "splendid-strand-452918-e6",
     "rawSql": "SELECT servicio_evento, COUNT(*) AS total\nFROM `emergencia_eventos.emergencias-macheadas`\nGROUP BY servicio_evento\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Evolución temporal del número de emergencias",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "project": "splendid-strand-452918-e6",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(timestamp_evento, MINUTE) AS minuto,\n  COUNT(*) AS total_eventos\nFROM\n  splendid-strand-452918-e6.`emergencia_eventos.emergencias-macheadas`\nWHERE\n  timestamp_evento >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR)\nGROUP BY\n  minuto\nORDER BY\n  minuto;\n"
    }
   ]
  }
 ]
}